"""Create the final diagnostic report from frozen records; never tune models."""
import hashlib,json,re
from pathlib import Path
import numpy as np
OUT=Path(__file__).parent;ROOT=OUT.parents[1]
config=json.loads((OUT/'frozen_acquisition_config.json').read_text());acq=json.loads((OUT/'acquisition_result.json').read_text());manifest=json.loads((OUT/'frozen_dataset_manifest.json').read_text());cache=json.loads((OUT/'cache_result.json').read_text());cal=json.loads((OUT/'calibration_results.json').read_text());export=json.loads((OUT/'kaggle_artifact_result.json').read_text());integrity=json.loads((OUT/'integrity_results.json').read_text());pipeline=json.loads((OUT/'pipeline_result.json').read_text())
old=json.loads((ROOT/'reports/carla_calibration_audit/separation_results.json').read_text())
def f(x):return f'{x:.9g}'
def span(values):return '['+', '.join(f(x) for x in values)+']'
def distribution(x):
 x=np.asarray(x,float)
 return {'min':float(x.min()),'p10':float(np.percentile(x,10)),'median':float(np.median(x)),'p90':float(np.percentile(x,90)),'max':float(x.max())}
lines=['# Frozen Acquisition Protocol','',f"Acquisition config SHA-256: `{acq['config_sha256']}`. Frozen before the first network request: first 10 complete official TRAIN scenarios in parsed archive order, whole scenarios, PCG64 seed 2026, 8 FIT / 2 CAL, causal window length 12, unchanged recipe definitions/default severities, feature/code hashes and production calibration audit.",'',config['study_role']+'. Preferred later target is N=20, 15 FIT / 5 CAL, under separate authorization. No final performance/generalization claims or automatic graph work.','', '# Network / Prefix Integrity','',f"Original prefix before/after: {acq['original_after']['bytes']:,} bytes, SHA-256 `{acq['original_after']['sha256']}`. Independent staging copy; no hardlink/symlink for the prefix. One replay of the staged original prefix reconstructed the live gzip/TAR state. Further bytes came through sequential HTTP Range streaming with 206/start/range/length/encoding checks and a stable server validator {acq['remote_validator']!r}.",'',f"Downloaded {acq['network_bytes']/1e9:.3f} GB additional compressed data. Expanded prefix is {acq['staged_bytes']/1e9:.3f} GB, SHA-256 `{acq['staged_sha256']}`. Remote TRAIN archive total advertised by Content-Range was {acq['remote_total_bytes']/1e9:.3f} GB; the rest was not acquired. All selected members were completely consumed; the full archive gzip trailer was deliberately not fetched.",'',f"Stopping evidence: `{json.dumps(acq['trailing_boundary'])}`. No scenario-ID prediction or performance-based selection. The parser stopped at that proven boundary; at most one 256 KiB compressed read chunk includes boundary read-ahead. No trailing scenario was extracted or classified complete. Logs: `{config['staging_root']}/acquisition_log.jsonl`.",'', '# 10 Complete TRAIN Scenarios','', '| Archive ordinal | Scenario | Partition | RGB/Seg frames | GNSS/IMU rows | Reused | First TAR offset |','|---|---|---|---|---|---|---|']
for r in manifest['scenarios']:
 t=r['tick_coverage'];lines.append(f"| {r['archive_ordinal']} | {r['scenario_id']} | {r['partition']} | {t['rgb_count']}/{t['seg_count']} | {r['tables']['gnss.feather']['rows']}/{r['tables']['imu.feather']['rows']} | {r['reused']} | {r['first_tar_member_offset']} |")
lines+=['','Every scenario has contiguous matching RGB/Seg tick coverage, complete member payloads, readable Base feather tables, finite required GNSS/IMU columns, aligned sensor rows/indexes, a strict TRAIN loader manifest and subsequent-header completion evidence. The frozen manifest records every source file size/SHA-256, table schemas/row counts, town, archive ordinal and source path. Original scenario-1/scenario-10 were verified against streamed archive hashes and never recopied or rewritten. Directory junctions provide a logical TRAIN-only view for the existing production builder.','', '# Frozen 8/2 FIT-CAL Manifest','',f"Dataset manifest SHA-256: `{(OUT/'frozen_dataset_manifest.sha256').read_text().strip()}`. It was frozen after all ten manifests validated, before any real model fitting.",'',f"FIT_NORMAL: {', '.join(manifest['FIT_NORMAL'])}.",'',f"CAL_NORMAL: {', '.join(manifest['CAL_NORMAL'])}.",'','The existing production rule sorted canonical IDs and applied NumPy PCG64 seed 2026; first round(0.25×10)=2 permuted IDs are CAL. No seed optimization. Production cache label TRAIN_NORMAL maps explicitly to FIT_NORMAL; CAL_NORMAL is unchanged. The accepted earlier proposal remains byte-identical.','', '# Multi-Scenario Cache','',f"Exactly one production cache build: {cache['clean_rows']:,} clean rows ({cache['FIT_rows']:,} FIT / {cache['CAL_rows']:,} CAL), plus {cache['CAL_pseudo_rows']:,} CAL-derived pseudo rows. Schema {cache['cache_schema_version']}, content SHA-256 `{cache['content_sha256']}`. NPZ size {cache['npz_bytes']:,} bytes; preprocessing wall time {cache['preprocessing_wall_s']/60:.2f} minutes.",'','Verified scenario/tick/partition coverage, finite features, complete hashes, CAL-only pseudo parents, target_normal=0 on pseudo rows, end_tick=parent_tick, start_tick=max(0,t−11), and exact parent features in every untouched modality block. No future/cross-scenario windows, FIT/CAL leakage or second determinism rebuild. Cache binding sidecar connects the frozen acquisition/dataset identities.','', '# Four-Agent Calibration Validity','', '| Agent | FIT scenarios/rows | CAL scenarios/normal/pseudo rows | Numerical convergence | Gradient norm | Minimum curvature | Pooled member structure | Boundary trend | finite_optimum |','|---|---|---|---|---|---|---|---|---|']
for name,r in cal['agents'].items():
 a=r['audit'];lines.append(f"| {name} | {r['FIT_scenarios']}/{r['FIT_rows']} | {r['CAL_scenarios']}/{r['CAL_normal_rows']}/{r['CAL_pseudo_rows']} | {a['optimizer_converged']} | {f(a['gradient_norm'])} | {f(a['minimum_curvature'])} | {a['separation']['pooled_members']['classification']} | {a['boundary_trend']} | {a['finite_optimum']} |")
lines+=['','| Agent | Normal member range | Pseudo member range | Member overlap | Mean-score gap | Best mean threshold | Violations / observations |','|---|---|---|---|---|---|---|']
for name,r in cal['agents'].items():
 a=r['audit'];g=a['separation']['ensemble_mean'];m=a['separation']['pooled_members'];lines.append(f"| {name} | {span(m['normal_range'])} | {span(m['pseudo_range'])} | {span(m['overlap_interval']) if m['overlap_interval'] else 'none'} | {f(g['gap'])} | {f(g['best_threshold'])} | {g['violations']}/{r['CAL_normal_rows']+r['CAL_pseudo_rows']} |")
lines+=['','`calibration_results.json` records complete mean/member distributions and overlap, all threshold diagnostics, fitted mapping parameters, Jensen diagnostics, fixed/relative slope curves and optimization status. Thresholds are diagnostics only. Production ensemble-predictive BCE and validity rule are unchanged. Accepted finite candidates are numerical stationary evidence, not global-existence proofs. Invalid scientific probability/UQ is null; raw scores and objective diagnostics remain available.','', '# 2-Scenario vs 10-Scenario Diagnosis','', '| Agent | Two-scenario geometry / violations | Ten-scenario geometry / violations | Two-scenario valid | Ten-scenario valid |','|---|---|---|---|---|']
comparison={}
for name,r in cal['agents'].items():
 o=old['agents'][name];og=o['audit']['separation']['ensemble_mean'];ng=r['audit']['separation']['ensemble_mean'];on=o['n_normal']+o['n_pseudo'];nn=r['CAL_normal_rows']+r['CAL_pseudo_rows']
 lines.append(f"| {name} | {og['classification']}; {og['violations']}/{on} ({100*og['violations']/on:.4f}%) | {ng['classification']}; {ng['violations']}/{nn} ({100*ng['violations']/nn:.4f}%) | {o['audit']['finite_optimum']} | {r['calibration_valid']} |")
 comparison[name]={'two_scenario':{'mean_geometry':og,'member_geometry':o['audit']['separation']['pooled_members'],'valid':o['audit']['finite_optimum'],'violations_fraction':og['violations']/on},'ten_scenario':{'mean_geometry':ng,'member_geometry':r['audit']['separation']['pooled_members'],'valid':r['calibration_valid'],'violations_fraction':ng['violations']/nn}}
 with np.load(ROOT/'reports/carla_calibration_audit'/f'{name.lower()}_member_scores.npz',allow_pickle=False) as z:
  M,y=z['member_scores'],z['target_normal']
  comparison[name]['two_scenario']['raw_score_distributions']={label:{'pooled_members':distribution(M[y==target].ravel()),'ensemble_mean':distribution(M[y==target].mean(axis=1))} for label,target in [('normal',1),('pseudo',0)]}
 comparison[name]['ten_scenario']['raw_score_distributions']={label:{'pooled_members':r['member_score_distributions'][label],'ensemble_mean':r['ensemble_mean_distributions'][label]} for label in ['normal','pseudo']}
lines+=['','| Agent / CAL class | Two-scenario mean score p10/median/p90 | Ten-scenario mean score p10/median/p90 |','|---|---|---|']
for name,c in comparison.items():
 for label in ['normal','pseudo']:
  old_d=c['two_scenario']['raw_score_distributions'][label]['ensemble_mean'];new_d=c['ten_scenario']['raw_score_distributions'][label]['ensemble_mean']
  lines.append(f"| {name} / {label} | {f(old_d['p10'])}/{f(old_d['median'])}/{f(old_d['p90'])} | {f(new_d['p10'])}/{f(new_d['median'])}/{f(new_d['p90'])} |")
valid_names=[n for n,r in cal['agents'].items() if r['calibration_valid']];invalid_names=[n for n,r in cal['agents'].items() if not r['calibration_valid']]
lines+=['',f"Ten-scenario accepted finite candidates: {', '.join(valid_names) or 'none'}. Invalid: {', '.join(invalid_names) or 'none'}. Camera/GNSS: "+'; '.join(f"{n}: old valid={old['agents'][n]['audit']['finite_optimum']}, new valid={cal['agents'][n]['calibration_valid']}, new member structure={cal['agents'][n]['audit']['separation']['pooled_members']['classification']}" for n in ['Camera','GNSS'])+'.','', 'Additional FIT/CAL diversity is the only scientific change. This descriptive checkpoint comparison has different training/CAL scenarios and row counts; it does not establish generalization or causal performance improvement. No model/recipe/calibration changes follow from the comparison.','', '# UQ Status','', 'Unchanged: total=H(mean p_t), aleatoric=mean H(p_t), epistemic=max(0,total−aleatoric). The following distributions use validated mappings only, on CAL clean versus modality-matched pseudo rows.','', '| Agent / CAL class | prob_normal p10/median/p90 | Total median | Aleatoric median | Epistemic p10/median/p90/max |','|---|---|---|---|---|']
for name,r in cal['agents'].items():
 if r['scientific_probability_and_uq'] is None:continue
 for label,d in r['scientific_probability_and_uq'].items():
  p=d['prob_normal'];e=d['epistemic'];lines.append(f"| {name} / {label} | {f(p['p10'])}/{f(p['median'])}/{f(p['p90'])} | {f(d['total']['median'])} | {f(d['aleatoric']['median'])} | {f(e['p10'])}/{f(e['median'])}/{f(e['p90'])}/{f(e['max'])} |")
lines+=['','The reported medians and tails determine how the previous near-zero epistemic finding persists or changes; score-space standard deviation remains a separate diagnostic. No alternative epistemic definition or benchmark-selected cutoff was introduced. Invalid agents have no validated probability-space UQ summaries.','', '# Kaggle Handoff','',f"Prepared local compact checkpoint artifact: `{export['artifact_path']}`, {export['total_bytes']:,} bytes, {export['n_rows']:,} rows. No raw archive, images, graph samples or graph training. It contains compact features, five member scores per agent, scenario/town/tick/partition dictionaries, per-agent validity/status, nullable probabilities/UQ, clean-vs-pseudo and per-agent targets, pseudo parent/recipe/severity/seed/window provenance, fitted one-class parameters, calibration parameters/audits and version/hash manifests.",'','Invalid probability/total/aleatoric/epistemic use NaN with an explicit validity mask (scientific null). Target semantics are constructed normality, never physical safety. Only CAL pseudo examples exist at this milestone; they are reserved for calibration and must not be repurposed as graph training data. FIT-derived graph pseudo generation and paired-seed StandardGAT/EpistemicGAT training require a later stage.','', '# Storage / Timing','',f"Acquisition including copy/replay/validation: {acq['elapsed_s']/60:.2f} minutes. Preprocessing: {cache['preprocessing_wall_s']/60:.2f} minutes. Pipeline total: {pipeline['total_pipeline_wall_s']/60:.2f} minutes. Expanded prefix: {integrity['storage']['staged_prefix_bytes']/1e9:.3f} GB; new raw extraction: {integrity['storage']['new_extracted_raw_bytes']/1e9:.3f} GB; cache total: {integrity['storage']['cache_total_bytes']/1e6:.3f} MB; compact handoff: {integrity['storage']['handoff_total_bytes']/1e6:.3f} MB. Existing original prefix/scenarios/caches remain separately preserved.",'', '# Tests / Core Integrity','']
for label,filename in [('Focused','focused_tests.txt'),('Broad requested regression','broad_tests.txt')]:
 text=(OUT/filename).read_text();matches=re.findall(r'=+\s*([^\n]*passed[^\n]*)\s*=+',text)
 lines.append(f"{label}: {matches[-1].strip('= ') if matches else 'see '+filename}.")
lines+=['','23 new acquisition tests cover partial compressed/TAR state, boundary-based completeness, safe paths/links/checksums, verified reuse without overwrite, PAX/GNU names, Range rejection and valid gzip termination. Baseline 482; expected new broad total 505. Existing source/test hashes match the frozen initial inventory; generic/frozen code and accepted calibration/recipe implementations are unchanged. Bare import cognix loads no adapters. Original prefix and all prior probe/cache artifacts are preserved. No TEST access, GAT/conformal, severity/threshold/calibration tuning, commits or pushes.','', 'New source/test files: `cognix/adapters/carla/train_acquisition.py`, `tests/unit/test_carla_train_acquisition.py`. New milestone scripts/manifests/logs/results/report are explicitly listed in `integrity_results.json`. No pre-existing source/test file was modified.','', '# Ready / Not Ready for 20-Scenario Expansion','', 'Engineering path is ready for a separately authorized N=20 protocol if storage/transport checks remain satisfied. Preserve this intermediate checkpoint and freeze a new 15/5 manifest without optimizing seeds or reacting to performance. No expansion to 20 has begun.','', '# Ready / Not Ready for GAT','', 'Not ready to start GAT at this intermediate checkpoint. Preferred development dataset is N=20 first, subject to separate authorization; any remaining invalid calibrations must stay unavailable. Graph target/sampling/evaluation decisions require their own preregistration.','', '# Recommended Next Step','', 'Review this ten-scenario diagnostic checkpoint, then separately authorize the twenty-scenario TRAIN expansion if desired. Keep calibration and recipes unchanged; preserve all checkpoint artifacts. Stop here: no further download, graph training, TEST access or tuning.']
diagnosis=("Camera's earlier suspected-separation flag is absent at N=10, but that does not validate its mapping: overlap expanded substantially, mean-score threshold violations increased from 22/3856 (0.5705%) to 859/7712 (11.1385%), and the optimizer exhausted 300 iterations without convergence. Its fitted positive slope is about 8.59e-7, with very small gradient/curvature; the unchanged validity rule rejects this numerical result. No claim about mathematical nonexistence of a Camera finite optimum follows. GNSS remains strictly separated at member level, with zero threshold violations and a positive gap. Therefore the unregularized mathematical MLE remains non-finite. Additional scenario diversity did not produce valid Camera/GNSS mappings. Seg and IMU retain accepted finite stationary candidates with positive local curvature. All ten scenarios are Town01; this is scenario diversity within one town, not cross-town validation.")
lines.insert(lines.index('# UQ Status')-1,diagnosis)
uq_interpretation=("The previous near-zero probability-space epistemic finding persists for typical observations, while nonzero tails are now explicitly visible. Seg medians are 3.12476e-6 (normal) and 1.02993e-12 (pseudo); IMU medians are 3.71955e-11 (normal) and exactly 0 (pseudo). Normal/pseudo p90 epistemic values are 7.44149e-5/6.65905e-5 for Seg and 9.53268e-5/2.82082e-4 for IMU. Maxima are 0.00318025/0.00112734 for Seg and 0.00492400/0.00276610 for IMU. Entropies use the unchanged natural-log production convention. Thus this is not identically zero disagreement, but typical probability-space epistemic remains small despite additional scenarios. No alternative epistemic definition or selected cutoff is introduced, and invalid Camera/GNSS mappings contribute no validated UQ.")
for i,line in enumerate(lines):
 if line.startswith('The reported medians and tails determine'):lines[i]=uq_interpretation
 if 'Baseline 482; expected new broad total 505.' in line:lines[i]=line.replace('Baseline 482; expected new broad total 505.','Broad total 505 = accepted baseline 482 + 23 new acquisition tests; zero failures.')
(OUT/'comparison_results.json').write_text(json.dumps(comparison,indent=2));(OUT/'report.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
integrity['new_report_files']=sorted(p.relative_to(ROOT).as_posix() for p in OUT.iterdir() if p.is_file())
(OUT/'integrity_results.json').write_text(json.dumps(integrity,indent=2))
print('Saved complete milestone report')
