"""Manifest/design writer only: no models, pseudo generation, or graph samples."""
import hashlib,json,subprocess,sys
from datetime import datetime,timezone
from pathlib import Path
import numpy as np

ROOT=Path(__file__).resolve().parents[2];OUT=Path(__file__).parent
N20=ROOT/'reports/carla_train_expand20_v1'
def read(p):return json.loads(Path(p).read_text(encoding='utf-8'))
def sha(p):
 h=hashlib.sha256()
 with Path(p).open('rb') as f:
  for b in iter(lambda:f.read(8<<20),b''):h.update(b)
 return h.hexdigest()
def save(name,obj):
 raw=(json.dumps(obj,sort_keys=True,indent=2,allow_nan=False)+'\n').encode()
 with (OUT/name).open('xb') as f:f.write(raw)
def doc(name,s):
 with (OUT/name).open('xb') as f:f.write(s.encode('utf-8'))
def git(*args):return subprocess.check_output(['git',*args],cwd=ROOT,text=True).strip()
config=read(N20/'frozen_acquisition_config.json');manifest=read(N20/'frozen_dataset_manifest.json')
stage=Path(config['staging_root']);cache=stage/'cache_train20_v1';handoff=stage/'kaggle_compact_train20_v1'
if '--snapshot-only' in sys.argv:
 paths=subprocess.check_output(['git','ls-files','--cached','--others','--exclude-standard'],cwd=ROOT,text=True).splitlines()
 hashes={}
 for rel in sorted(set(paths)):
  p=ROOT/rel
  if p.is_file() and not p.is_relative_to(OUT):hashes[rel]=sha(p)
 outside={str(p):sha(p) for folder in [cache,handoff] for p in sorted(folder.iterdir()) if p.is_file()}
 save('initial_state.json',{'repository_sha256':hashes,'N20_cache_and_handoff_sha256':outside,'git_head':git('rev-parse','HEAD'),'git_status':git('status','--short'),'snapshot_utc':datetime.now(timezone.utc).isoformat()})
 print('Snapshot complete:',len(hashes),'repository files;',len(outside),'cache/handoff files');sys.exit(0)

base=read(OUT/'initial_state.json')
for rel,h in base['repository_sha256'].items():assert sha(ROOT/rel)==h,rel
for p,h in base['N20_cache_and_handoff_sha256'].items():assert sha(p)==h,p
assert git('rev-parse','HEAD')==base['git_head']
for rel,h in config['source_hashes'].items():assert sha(ROOT/rel)==h,rel
cr=read(N20/'cache_result.json');er=read(N20/'kaggle_artifact_result.json');cal=read(N20/'calibration_results.json')
assert sha(cache/'carla_train_cache.npz')==cr['file_sha256']
assert sha(handoff/'manifest.json')==er['export_manifest_sha256']
assert sha(N20/'frozen_dataset_manifest.json')==(N20/'frozen_dataset_manifest.sha256').read_text().strip()
assert {k:v['calibration_valid'] for k,v in cal['agents'].items()}=={'Camera':True,'Seg':True,'GNSS':False,'IMU':True}
hm=read(handoff/'manifest.json')
for name,r in hm['files'].items():assert sha(handoff/name)==r['sha256']
with np.load(handoff/'compact_training_checkpoint.npz',allow_pickle=False) as z:
 assert z['calibration_valid'].tolist()==[True,True,False,True]
 for key in ['prob_normal','total','aleatoric','epistemic']:assert np.isnan(z[key][:,2]).all()
 assert np.all(z['partition'][z['is_pseudo']]==1)

ids=sorted(manifest['FIT_NORMAL']);rng=np.random.Generator(np.random.PCG64(2027));perm=rng.permutation(len(ids))
val=sorted(ids[int(i)] for i in perm[:3]);train=sorted(set(ids)-set(val))
assert len(train)==12 and len(val)==3 and not(set(ids)&set(manifest['CAL_NORMAL']))
mapping={sid:('GRAPH_TRAIN' if sid in train else 'GRAPH_VALIDATION' if sid in val else 'AGENT_CAL_ONLY') for sid in manifest['sorted_canonical_ids']}
split={'schema_version':1,'source_N20_manifest_sha256':sha(N20/'frozen_dataset_manifest.json'),'seed':2027,'rng':'NumPy Generator(PCG64(2027))','numpy_version':np.__version__,
 'rule':'sort frozen FIT IDs; permute once; first 3 positions are graph validation; remaining 12 graph train; sort each output list',
 'permutation_indices':perm.tolist(),'sorted_FIT_ids':ids,'GRAPH_TRAIN':train,'GRAPH_VALIDATION':val,'AGENT_CAL_ONLY':manifest['CAL_NORMAL'],'scenario_role':mapping,
 'pseudo_inherits_parent_role':True,'tick_level_random_splitting':False,'held_out_unit':'whole scenario',
 'conditional_validation_limit':'Frozen upstream one-class models used all 15 FIT scenarios, including these 3 validation scenarios. This holds out graph-supervised fitting only; it is not full-pipeline unseen-scenario evaluation. No upstream refitting is performed.',
 'CAL_usage':'existing agent calibration only; no graph fitting, early stopping, threshold selection, or graph-development metrics'}
save('split_manifest.json',split)

schema={'schema_version':1,'unit':'one scenario/tick/constructed observation; not a temporal graph','node_order':['Camera','IMU','Seg'],'handoff_agent_indices':[0,3,1],
 'node_count':3,'node_features':{'order':['prob_normal','epistemic','aleatoric'],'shape':[3,3],'model_dtype':'float32','source_computation_dtype':'float64','units':['probability','natural-log entropy nats','natural-log entropy nats'],'fitted_scaler':None,'raw_compact_features_in_primary_node_vector':False,'total_omitted_reason':'total=aleatoric+epistemic is redundant'},
 'attention_side_channel':{'epistemic':'same canonical per-node E as feature column 1; use unchanged generic sender prior','sender_only':True,'standard_prior':'all ones','epistemic_prior':'1/(1+E_j)','strength':1,'normalization':None,'target_uncertainty_modifier':None},
 'topology':{'matrix':[[0,1,1],[1,0,1],[1,1,0]],'entry_semantics':'A[i,j]=1 means sender j communicates to receiver i','directed_edges':[[0,1],[0,2],[1,0],[1,2],[2,0],[2,1]],'edge_pair_semantics':'[sender,receiver]','self_edges':False,'automatic_self_loop_insertion':False,'spatial_edges':False},
 'target_normal':{'clean':1,'single_valid_modality_pseudo':0,'meaning':'constructed normal-vs-controlled-corruption discrimination; neither official anomaly probability nor driving safety'},
 'per_node_target':'1 for every clean/untouched node; 0 only for the single corrupted valid node; provenance only, no auxiliary node loss',
 'required_provenance':['row_key','pair_key','scenario_id','town','parent_tick','source_split','N20_partition','graph_split','is_pseudo','target_normal','target_normal_per_node','corrupted_agent','recipe_id','severity','generator_seed','generator_base_seed','window_start_tick','window_end_tick','source_hash_bundle_sha256','cache_content_sha256','calibration_parameters_sha256','feature_extractor_sha256','pseudo_registry_sha256','protocol_sha256','node_order','graph_content_sha256'],
 'row_key_encoding':{'pair_key':'SHA256(UTF8 canonical sorted compact JSON {scenario_id,parent_tick,protocol_sha256}))','row_key':'SHA256(UTF8 canonical sorted compact JSON {pair_key,is_pseudo,recipe_id,severity,generator_seed}))','clean_null_fields':['recipe_id','severity','generator_seed','corrupted_agent'],'missing_is_null_not_zero':True},
 'graph_content_hash':'SHA256 of UTF8 sorted compact JSON provenance excluding graph_content_sha256, followed by C-contiguous little-endian float32 node_features bytes, little-endian float64 canonical epistemic side-channel bytes, and C-contiguous uint8 adjacency bytes; shapes/orders fixed here',
 'canonical_row_order':'sort by (scenario_id,parent_tick,is_pseudo), clean before pseudo; identical data order and row keys for all methods/seeds',
 'epistemic_side_channel_storage':'float64 canonical E supplied identically to both GATs; existing generic compute_epistemic_weights computes Python-float prior then stores float32, while model node features are cast to float32',
 'untouched_nodes':'copy exact parent compact features AND canonical p/E/A; never zero-fill, re-corrupt, or re-extract clean features',
 'pseudo_sampling_reference':'protocol.json::FIT_graph_pseudo_policy','data_generation_performed':False,
 'secondary_auxiliary':{'GNSS_node_present':False,'inputs':['mean of 5 raw GNSS normality scores','population std of those 5 raw scores (ddof=0)'],'GNSS_prob_normal':None,'GNSS_UQ':None,'source':'same parent clean GNSS member scores for both members of every pair; no GNSS-only pseudo'}}
save('graph_schema.json',schema)

metrics={'schema_version':1,'evaluation_role':'internal graph-development validation, not independent test performance','positive_class':'corruption: y_corruption=1-target_normal','score':'p_corruption=1-q_normal',
 'primary_endpoint':{'name':'scenario_macro_AUROC','formula':'arithmetic mean of AUROC over the 3 frozen graph-validation scenarios; ties contribute 0.5','primary_contrast':'EpistemicGAT minus StandardGAT'},
 'secondary':['scenario-macro average precision (AUPRC as stepwise average precision, not trapezoidal PR integration)','scenario-macro corruption F1','scenario-macro accuracy','scenario-macro balanced accuracy','scenario-macro Brier score','scenario-macro binary probability ECE','scenario-macro BCE','pooled versions of all metrics','per-scenario and per-recipe descriptive results'],
 'Brier':'mean((q_normal-target_normal)^2)','BCE':'mean(-y*log(clip(q,1e-7,1-1e-7))-(1-y)*log(clip(1-q,1e-7,1-1e-7)))',
 'ECE':{'kind':'binary probability reliability, not max-class-confidence ECE','bins':15,'edges':'k/15 for k=0..15','membership':'[lower,upper), last bin includes 1','formula':'sum_b (n_b/n)*abs(mean(q_normal_b)-mean(target_normal_b))','empty_bins':'zero contribution'},
 'threshold':{'select_using':'graph validation only, separately for each method and seed at its selected checkpoint','candidate_set':'sorted unique validation p_corruption values union {0,1}','classify':'corruption iff p_corruption>=tau','objective':'maximize arithmetic mean of per-validation-scenario corruption F1','tie_break':'largest tau','zero_denominator_F1':0,'optimism':'threshold selection and reported validation F1 use the same validation data; report as development statistics, not confirmatory evaluation'},
 'checkpoint_selection':'validation scenario-macro BCE only; no AUROC, F1 or CAL outcomes used to select checkpoints','undefined':'null plus explicit reason; no silent imputation, replacement scenario, or dropping failed seed',
 'class_balance':'exact 1:1 clean/pseudo among eligible paired parents; report realized rows, recipe counts and all skips; this is an artificial prevalence',
 'paired_statistics':{'seeds':[101,202,303,404,505],'retain_all_seeds':True,'per_seed':'same samples/splits; record primary contrast and all oriented secondary differences','summaries':['mean paired difference','median paired difference','sample SD of paired differences','min/max','all five individual differences'],
 'conditional_seed_CI':'mean(delta) +/- 2.776445105*SD(delta)/sqrt(5); t interval describes seed variability conditional on this fixed validation set, not population generalization',
 'effect_size':'paired dz=mean(delta)/SD(delta); null if SD=0',
 'exact_sign_flip':{'tail':'two-sided','enumeration':32,'statistic':'abs(mean(delta))','p':'fraction of all 32 sign assignments with abs(mean(s*delta)) >= observed statistic - 1e-12','all_zero_differences_p':1,'minimum_attainable_two_sided_p':0.0625,'claim':'five pairs cannot reach p<0.05 with this exact two-sided test; no superiority claim from one seed or this fixed development set'},
 'scenario_bootstrap':{'draws':10000,'seed':606,'unit':'whole validation scenario, keeping all ticks, clean/pseudo pairs and methods together','calculation':'sample 3 scenario IDs with replacement; compute equal-scenario mean contrast, then mean across the five paired seeds; percentile interval [2.5,97.5]','scope':'descriptive fragility check with only 3 validation scenarios; not independent test CI; never bootstrap individual ticks'},
 'failures':'retain failed runs and reason; no seed replacement or best-seed selection; confirmatory-style aggregate marked incomplete if any planned pair fails','secondary_inference':'exploratory only; no uncorrected multi-metric superiority claims; NoGraph contrasts descriptive'}}
save('metrics_spec.json',metrics)

execution='''# Kaggle execution plan (design only)

This file specifies a future authorized run. No notebook, trainer, graph dataset, upload or training is executed in this milestone. Use one T4, one process, no distributed training.

## Inputs and present readiness gate

The N=20 compact handoff supplies clean FIT features/agent outputs and CAL pseudo rows. It does **not** contain FIT pseudo examples. Camera/Seg corruptions require the preserved raw TRAIN frames; the compact features cannot reconstruct those pixel recipes. Therefore first implement the separately authorized local FIT-only pseudo export using the frozen protocol and original extractors. Export compact features/scores/probabilities/UQ plus provenance; keep raw images outside Kaggle. Do not synthesize corruptions directly in embedding space. CAL pseudo rows are rejected by the graph data loader.

## Ordered workflow

1. Verify SHA256SUMS, protocol/schema hashes, N=20 source/cache/handoff hashes, canonical node order and validity masks. Require GNSS probability/UQ to remain null. Pin/log Python, NumPy, PyTorch, CUDA and dependency lock versions from the future validated environment; no runtime dependency upgrades.
2. Generate FIT pseudo **locally** after explicit authorization, or load the matching compact FIT-only export. Reuse every clean compact parent row. Apply only the frozen five recipes with base seed 0 and production per-tick seed t. Check hash/provenance, causal windows, non-effect guard, exact untouched nodes and per-node labels. A no-effect parent loses both members of the pair. Do not load any CAL pseudo as graph training data. Publish one canonical row-keyed dataset and skip ledger before model initialization.
3. Verify split_manifest.json exactly; never resplit in the notebook. Group clean/pseudo by parent scenario. Accept only the 12 GRAPH_TRAIN and 3 GRAPH_VALIDATION scenarios. Assert CAL intersection is empty. Materialize float32 [B,3,3] node tensors, immutable adjacency and raw-E prior inputs from float64 canonical agent outputs. No fitted normalization and no recalibration.
4. Implement the preregistered future report/adapter-side trainer. Compose the unchanged generic GAT layers with a batched wrapper; the current generic .fit is a per-observation loop and is not the frozen mini-batch trainer. Verify vectorized equivalence to unmodified layers, receiver/sender direction, no self-loops, same parameter count, neutral-prior identity and monotonic sender suppression on synthetic fixtures. Do not edit generic production or frozen synthetic code. Implement the separate NoGraph shared MLP; do not substitute the frozen identity NoGraph plugin.
5. For seeds 101,202,303,404,505, train NoGraph, then StandardGAT, then EpistemicGAT with the same data and explicit epoch permutations. Reset Python/NumPy/Torch/CUDA RNGs for every run. Standard/Epistemic initial parameter tensors are cloned identically per seed; match initial dropout RNG state. Each uses the same maximum budget/early-stop rule. No hyperparameter search.
6. Use float32, Adam(lr=0.001, weight_decay=0.0001), batches of 256, maximum 100 epochs, dropout 0.1, no AMP, scheduler, gradient clipping or multi-GPU. Set CUBLAS_WORKSPACE_CONFIG=:4096:8 before CUDA initialization; disable TF32 and cuDNN benchmarking; enable deterministic algorithms. DataLoader workers=0. If a nondeterministic operation is rejected, stop and record it; no silent fallback. Construct each epoch's identical graph-row permutation using PCG64(seed+epoch_index), independent of the Torch dropout RNG.
7. Evaluate only GRAPH_VALIDATION, with dropout disabled. Monitor equal-scenario BCE. The patience tracker updates only when loss improves by more than 1e-5; otherwise increment its counter, stopping after 10 such epochs. Independently save the lowest-loss checkpoint among executed epochs, earliest epoch on exact ties. Use no CAL/TEST outcome for early stopping, scaling, sampling, architecture or threshold selection.
8. Save per-run checkpoints (including optimizer/RNG states), run config and environment, epoch histories, best epoch, failure status and protocol/data/source hashes. Save row-keyed predictions for GRAPH_TRAIN and GRAPH_VALIDATION: scenario, tick, pair/row keys, recipe, role, true target, q_normal, p_corruption and method/seed/checkpoint hash. Persist per-layer evaluation attention for the same frozen validation rows; do not choose visually favorable rows after seeing performance.
9. Select the corruption threshold exclusively from graph validation as metrics_spec.json defines. Save every seed's per-scenario and pooled metrics, per-recipe diagnostic counts, all paired differences and the predefined small-sample statistical summaries. No best-seed model or sample selection. These are development results, since validation also selects checkpoints/thresholds and upstream one-class agents used all FIT scenarios.
10. After all primary outputs are frozen, run the single exploratory GNSS-raw auxiliary-input condition with the same samples/splits/seeds and explicit secondary architecture. Keep it separate from primary tables. Do not introduce GNSS-only pseudo or a GNSS calibrated probability/UQ. Save all failures and negative results.

## Release gates

Kaggle training is not executable from the present handoff alone. It requires an authorized FIT-only compact graph export, a tested report/adapter-side trainer, exact protocol/schema/hash validation and an environment lock. Do not upload or launch here. Conformal calibration occurs only after graph methodology/model selection is frozen and its separate independence/exchangeability protocol is approved. No official TEST is accessed.
'''
doc('kaggle_execution_plan.md',execution)

proto={'protocol_version':'carla_gat_preregistration_v1','status':'FROZEN_DESIGN_ONLY','frozen_at_utc':datetime.now(timezone.utc).isoformat(),
 'primary_research_question':'Does explicitly incorporating valid epistemic uncertainty into graph attention improve collective normal-vs-corruption prediction relative to graph attention without the epistemic prior, under matched data, architecture capacity and paired random seeds?',
 'primary_methods':['NoGraph','StandardGAT','EpistemicGAT'],'primary_modalities':['Camera','Seg','IMU'],'node_order':schema['node_order'],
 'GNSS_primary_policy':{'excluded':True,'basis':'frozen scientific calibration-validity rule, not downstream graph performance','calibrated_probability':None,'UQ':None,'no_recalibration_or_regularization':True},
 'bindings':{'N20_acquisition_config_sha256':sha(N20/'frozen_acquisition_config.json'),'N20_dataset_manifest_sha256':sha(N20/'frozen_dataset_manifest.json'),'N20_cache_file_sha256':cr['file_sha256'],'N20_cache_content_sha256':cr['content_sha256'],'N20_cache_schema_version':2,'N20_handoff_manifest_sha256':er['export_manifest_sha256'],'agent_calibration_results_sha256':sha(N20/'calibration_results.json'),
 'source_code_sha256':config['source_hashes'],'generic_graph_source_sha256':{rel:sha(ROOT/rel) for rel in ['cognix/graph/epistemic_gat.py','cognix/graph/standard_gat.py','cognix/graph/no_graph.py']},'git_head':base['git_head'],'fitted_oneclass_parameters_sha256':sha(handoff/'fitted_oneclass_parameters.npz'),'all_cache_handoff_file_sha256':base['N20_cache_and_handoff_sha256'],
 'preregistration_dependencies_sha256':{name:sha(OUT/name) for name in ['graph_schema.json','split_manifest.json','metrics_spec.json','kaggle_execution_plan.md']}},
 'FIT_graph_pseudo_policy':{'execute_this_milestone':False,'source_split':'official train','parents':'frozen FIT_NORMAL only; no CAL','ticks':'every cached parent tick 1..2999, once','max_pseudo_per_parent':1,
 'recipe_order':['camera_brightness_shift','camera_occlusion','seg_region_corruption','imu_spike','imu_bias_scale'],'selection':'recipe_order[t % 5]; same production rotation rule with eligibility subset fixed by primary modality validity',
 'excluded_recipes':['gnss_bias','gnss_drift'],'exclusion_reason':'a GNSS-only corruption leaves all three primary nodes unchanged and would create an invisible graph target; eligibility follows modality policy, not downstream performance',
 'severity':{k:v for k,v in config['pseudo']['default_severities'].items() if not k.startswith('gnss')},'generator_base_seed':0,'generator_call_seed':'base_seed+t = t, exactly the existing _pseudo_for_scenario/_generate scheme; registry uses explicit PCG64 seed','source_registry_unchanged':True,
 'window_length':12,'window':'temporal IMU corrupts [max(0,t-11),t] only; Camera/Seg corrupt instantaneous tick t; parent window metadata always records causal bounds','untouched_features':'copy exact clean parent blocks; no repeated clean feature extraction',
 'balance':'one clean graph plus one accepted pseudo graph per eligible parent, exact 1:1; maximum 35,988 clean+35,988 pseudo train, 8,997 clean+8,997 pseudo validation',
 'no_effect':'unchanged compact-modality np.allclose(rtol=1e-12,atol=1e-12) guard; remove both graph pair members if no effect, no resampling or fallback recipe; original cache is untouched',
 'future_adapter_contract':'Read immutable N20 clean arrays and FIT whitelist; never call _scenario_rows or rebuild the N20 cache. Call unchanged _pseudo_for_scenario(raw, cached_parent_features, scenario_id, frozen_five_recipe_tuple, 0, 1, None) after enforcing FIT/TRAIN gates and window 12. Score corrupted features with loaded fitted_oneclass_parameters and fixed accepted calibrators, without any .fit call. Reuse cached clean p/E/A and exact untouched modality blocks. Export separate FIT-only arrays/provenance/skip ledger, never overwrite N20.',
 'other_errors':'missing inputs, nonfinite features or invalid required p/UQ fail closed; record issue without replacing a scenario or recipe','node_output_collisions':'retain accepted compact-feature corruptions even if p/E/A coincides after a noninjective/saturated score mapping; log collisions, never filter using model outcomes','sampling_frequencies':'fixed modulo rotation: Camera 2/5, Seg 1/5, IMU 2/5 up to endpoint counts and fixed no-effect skips; report realized counts','CAL_pseudo_reuse_for_graphs':False},
 'base_node_features':schema['node_features'],'information_matching':'Both GATs and NoGraph receive the identical p/E/A vector. EpistemicGAT reuses the same E through a fixed attention prior; this tests the prior contribution beyond E as an ordinary predictive covariate.',
 'GAT_architecture':{'layers':2,'heads_per_layer':1,'input_dim':3,'hidden_dim':8,'output_dim':1,'linear_bias':False,'attention_logit':'LeakyReLU(a^T[W h_i || W h_j], negative_slope=0.2)','intermediate_activation':'ELU','final_activation':'linear node logits; sigmoid only for node probability','dropout':0.1,'dropout_location':'post-softmax normalized attention, exactly existing layer','pooling':'q_normal=mean_i sigmoid(z_i); no extra fusion, belief or decision layer','parameter_count_each':50,'initialization':'Xavier uniform for every W and attention vector; identical cloned tensors per Standard/Epistemic seed'},
 'epistemic_attention':{'source':'unchanged cognix.graph.epistemic_gat.EpistemicGATLayerPT and compute_epistemic_weights','equations':['w_j=1/(1+E_j)','e_ij^epi=e_ij+log(w_j)=e_ij-log(1+E_j)','alpha_ij=exp(e_ij)*w_j/sum_{k in incoming_neighbors(i)} exp(e_ik)*w_k'],
 'scope':'same original canonical E_j at both layers; sender prior only, no receiver factor','neutral':'use_epistemic_prior=False gives w=1; if every E=0 both attention operators coincide','monotonic':'for fixed learned logits and other senders, increasing E_j decreases its normalized attention to each eligible receiver before dropout','units':'E is canonical entropy-gap in nats, not variance or its square root','division_by_zero':'1+E>=1; require finite nonnegative E','normalization_or_FIT_scale':None,'strength':'fixed 1, no search','floating_point':'reuse existing float32 prior/log implementation; tiny E can round to a neutral prior; accept weak/null effects without post-result amplification'},
 'NoGraph':{'name':'NoGraph shared-node MLP, distinct from frozen identity NoGraph plugin','architecture':'bias-free shared Linear(3,12) -> ELU -> Dropout(0.1) -> bias-free Linear(12,1); mean(sigmoid(node_logit))','parameters':48,'inputs':'same p/E/A; same fixed 3 nodes','message_passing':False,'initialization':'Xavier uniform; matching run seed','reason':'trainable nonlinear baseline with 48 parameters against 50 in each GAT; no deliberate information/capacity deficit','implementation':'future report/adapter-side classifier; frozen core identity NoGraph remains unchanged'},
 'training_specification':{'execute_this_milestone':False,'optimizer':'Adam','learning_rate':0.001,'weight_decay':0.0001,'batch_size_graphs':256,'maximum_epochs':100,'loss':'mean BCE(q_normal,target_normal) over graph-training samples; no node-label auxiliary loss','validation_loss':'equal-scenario mean BCE over 3 graph-validation scenarios','early_stopping':{'patience':10,'min_delta':0.00001,'minimum_epochs':1,'monitor_tracker':'reset only if loss < tracked_best-min_delta; update tracked_best only on such improvement','checkpoint':'independently save actual lowest validation BCE among executed epochs, earliest epoch on exact tie'},'seeds':[101,202,303,404,505],'shuffle':'PCG64(seed+zero_based_epoch_index); same row keys and permutation across all methods','scheduler':None,'gradient_clipping':None,'precision':'float32; no AMP or TF32','device':'single T4; no distributed training','upstream_agents_frozen':True},
 'GNSS_secondary':{'number_of_conditions':1,'label':'exploratory raw-GNSS auxiliary-input ablation','run_after_primary_outputs_frozen':True,'methods':['NoGraph','StandardGAT','EpistemicGAT'],'same_samples_splits_seeds':True,
 'GNSS_inputs':schema['secondary_auxiliary']['inputs'],'GNSS_node':False,'GNSS_epistemic_prior':None,'GNSS_probability_UQ':None,
 'readout':'sigmoid(b + w0*logit(clip(q_primary,1e-7,1-1e-7)) + w1*raw_GNSS_mean + w2*raw_GNSS_population_std)','head_initialization':'w0=1,w1=w2=0,b=0','trainable_parameters_added':4,'train_jointly_with_backbone_under_same_training_spec':True,
 'interpretation':'GNSS is uncalibrated context only, unchanged within clean/pseudo pairs; this does not evaluate GNSS-only corruption detection and cannot replace the primary three-agent experiment','no_new_GNSS_score_transform_or_calibration':True},
 'conformal_placement':{'fit_now':False,'stage':'after graph methodology/model selection and output pipeline are frozen; before later separately authorized held-out evaluation','candidate_nonconformity':'1-p_graph[true constructed class], subject to later scenario/exchangeability preregistration',
 'CAL_scenarios_reserved_from_graph_development':manifest['CAL_NORMAL'],'limitation':'All 5 current CAL scenarios already fitted upstream probability mappings. Reusing them naively for split conformal does not establish independent calibration or a coverage guarantee. A separate future protocol must resolve calibration independence and temporal/scenario exchangeability; no new acquisition or upstream refitting is authorized here.'},
 'interpretation_limits':['constructed pseudo distribution and artificial 1:1 prevalence','graph validation is reused for early stopping and threshold selection','upstream representation saw graph-validation FIT scenarios','three validation scenarios and five seeds provide limited inference','small canonical E may yield tiny/rounded-neutral float32 attention effects','no official TEST or physical-safety inference'],
 'authorization_boundary':{'current':'preregistration and deterministic metadata only','graph_generation':False,'any_training':False,'TEST_access':False,'new_data_acquisition':False,'conformal_fit':False,'calibration_feature_recipe_changes':False,'generic_or_synthetic_changes':False,'commit_push':False},
 'readiness':{'protocol_ready_for_future_FIT_graph_generation':True,'graph_generation_performed':False,'Kaggle_training_ready_now':False,'remaining_gates':['separate authorization for FIT-only pseudo implementation/export','tested adapter/report-side batched trainer and NoGraph classifier','generated compact FIT graph artifact with frozen splits/hashes/provenance','future execution environment lock and deterministic fixture checks'],'next_step':'authorize only the frozen FIT graph-data adapter/export and validation first; do not start training or TEST'}}
save('protocol.json',proto)
tests=(OUT/'nontraining_tests.txt').read_text()
assert '4 passed' in tests and 'failed' not in tests
integrity={'status':'passed','preserved_repository_files':len(base['repository_sha256']),'preserved_cache_handoff_files':len(base['N20_cache_and_handoff_sha256']),
 'repository_sha256_unchanged':True,'N20_cache_and_handoff_byte_hashes_unchanged':True,'calibration_feature_recipe_sources_unchanged':True,'generic_core_and_frozen_synthetic_unchanged':True,'GNSS_probability_UQ_still_null':True,'graph_samples_generated':0,'model_training_calls':0,'official_TEST_access':False,'new_network_or_data_acquisition':False,'conformal_fitting':False,'git_head_unchanged':True,'commits_pushes':False,'existing_nontraining_tests':'4 passed','modified_preexisting_scientific_files':[]}
save('integrity_results.json',integrity)

sections=[]
def section(title,text):sections.extend(['# '+title,'',text,''])
section('Primary Research Question',proto['primary_research_question']+'\n\nPrimary contrast is EpistemicGAT minus StandardGAT scenario-macro validation AUROC. NoGraph is a fair trainable comparison. These are fixed-representation development results, not independent held-out performance.')
section('Primary Modalities','Camera, Seg and IMU only, selected solely by the frozen N=20 calibration-validity rule. Canonical node order is Camera, IMU, Seg, corresponding to handoff indices 0, 3, 1. No downstream metrics or graph training were generated.')
section('GNSS Handling Decision','GNSS calibrated probability and UQ remain null. Preserve its raw member scores and underflow/separation diagnostics. One secondary exploratory condition adds mean and population standard deviation of its five raw scores to each methodâ€™s collective readout, with no GNSS node or prior. Its four-parameter logistic auxiliary head starts as the identity of the primary collective prediction and is trained jointly only in that future secondary condition. Use exactly the primary samples, splits and seeds; no GNSS-only corruptions. It measures raw-context contribution, not GNSS corruption detection, and cannot replace the primary experiment.')
section('Graph Sample / Target','One graph per scenario/tick/constructed observation, three valid agent nodes, six directed edges. Clean target_normal=1; single valid-modality controlled corruption target_normal=0. Untouched nodes retain exact parent features and agent outputs. Per-node targets are recorded but not optimized. This is constructed normal-vs-pseudo discrimination, not official CarlAnomaly anomaly probability or driving safety. Every sample carries canonical row/pair keys, scenario/town/tick, split, source hashes, recipe/severity/seed/window and upstream/protocol hashes; graph_schema.json specifies the complete contract.')
section('FIT Pseudo Sampling','No pseudo generation performed. Future parents are FIT_NORMAL only, ticks 1..2999. Frozen order: camera_brightness_shift, camera_occlusion, seg_region_corruption, imu_spike, imu_bias_scale. Select recipe[t % 5], max one pseudo per tick, production base seed 0 and call seed t. Original recipe definitions/default severities and causal window 12 stay unchanged. GNSS recipes are ineligible because their corruption would be invisible to all primary nodes; this is a modality-policy decision. Clean features are reused, and untouched blocks copied. The existing compact no-effect guard removes both members of a graph pair with no replacement, preserving exact 1:1 balance. Retain and report any later p/E/A collisions instead of filtering by predictive outcomes. Maximum dataset: 71,976 graph-train and 17,994 graph-validation rows before fixed guards; realized counts await the separately authorized export. CAL pseudo is never reused as graph-training data.')
section('Node Features','Each node receives [prob_normal, epistemic, aleatoric], with canonical entropy quantities in nats, from the accepted fixed agents. All three methods receive the same information. Total is redundant and omitted; raw high-dimensional representations and modality one-hot features are omitted. No fitted scaler. EpistemicGAT additionally routes the exact same E through its fixed sender attention prior, so the comparison isolates prior allocation beyond E as an ordinary covariate. Cast to float32 only at graph-model input; original agent calculations remain float64.')
section('Graph Topology','Receiver-row/sender-column adjacency is [[0,1,1],[1,0,1],[1,1,0]]. Fully connected directed communication among the three agents, six edges, no self-edges or automatic self-loops, no CARLA spatial relationships. All methods use the same node order and graph instances.')
section('NoGraph Specification','Future trainable shared-node MLP: bias-free 3â†’12â†’1, ELU between layers, hidden dropout 0.1, Xavier initialization, q_normal=mean(sigmoid(node_logit)). It uses all identical node inputs with no message passing and has 48 parameters against 50 per GAT. Use the same loss, optimizer, batches, validation rule and seeds. The frozen generic identity NoGraph plugin remains unchanged and is not substituted for this primary trainable baseline.')
section('StandardGAT Specification','Two single-head layers, input 3, hidden 8, output 1. Bias-free projections/attention, LeakyReLU(0.2) logits, ELU hidden layer, linear node output, post-softmax attention dropout 0.1, mean of node sigmoid probabilities. Adam lr=0.001, weight_decay=0.0001, batch size 256, maximum 100 epochs; graph BCE only. Early stopping: validation scenario-macro BCE, patience 10, min_delta=1e-5; save minimum observed BCE checkpoint, earliest exact tie. Xavier initialization; seeds 101,202,303,404,505. No scheduler, AMP, TF32, gradient clipping or search. Future report/adapter-side batching composes the unchanged generic layers; existing generic .fit is per-observation and is not the mini-batch execution path.')
section('EpistemicGAT Specification','Same graph data, p/E/A features, architecture, 50 trainable parameters and training specification as StandardGAT, with identical cloned initial tensors per seed. Reuse the existing generic mechanism at both layers:\n\n`w_j=1/(1+E_j)`\n\n`e_ij_epi=e_ij+log(w_j)=e_ij-log(1+E_j)`\n\n`alpha_ij=exp(e_ij)*w_j / sum_k(exp(e_ik)*w_k)` over incoming neighbors.\n\nHigher sender E reduces its attention for fixed logits; target E has no separate prior factor. E is the canonical entropy gap, not a standard deviation. The prior denominator 1+E is at least one; require finite nonnegative E. Prior-disabled/all-zero E reduces to ordinary attention. No learned strength, normalization or FIT-statistic amplification: fixed strength one in raw nats. Tiny E can round to a neutral float32 prior or produce weak effects; null results are acceptable and will not trigger strength tuning. Frozen synthetic implementation is unchanged. Learned node outputs are contributions to the graph readout, not newly calibrated modality probabilities.')
section('Graph Train / Validation Split','Seed 2027, PCG64 permutation of sorted frozen FIT IDs; first three positions validation, remaining twelve train.\n\nGRAPH_TRAIN: '+', '.join(train)+'.\n\nGRAPH_VALIDATION: '+', '.join(val)+'.\n\nCAL reserved: '+', '.join(manifest['CAL_NORMAL'])+'.\n\nPseudo inherits parent membership; whole scenarios only. The fixed one-class agents already fitted all 15 FIT scenarios. This is a supervised graph holdout conditional on a fixed representation that saw validation scenarios, not full-pipeline unseen-scenario evaluation. No agent refit occurs. Graph-validation data alone controls early stopping and thresholds; CAL is excluded from graph development.')
section('Metrics','Primary: equal-scenario macro AUROC on corruption probability 1âˆ’q_normal. Secondary: average precision/AUPRC, corruption F1, accuracy, balanced accuracy, Brier, binary probability ECE, BCE and pooled/per-scenario/per-recipe versions. ECE: 15 fixed equal-width probability bins, left-closed/right-open except final inclusive edge, sample-weighted absolute mean probability/target gap. Select a per-method/per-seed corruption threshold using graph-validation macro F1 over unique probabilities plus 0/1; largest threshold on ties, corruption iff pâ‰¥threshold. F1 is development/selection-reused, not independent test performance. Report artificial 1:1 prevalence, no-effect skips and every undefined metric as null with reason. metrics_spec.json freezes every formula and tie rule.')
section('Paired-Seed Statistical Plan','Seeds [101,202,303,404,505] for all stochastic methods. Same rows, split and epoch shuffles for every method; identical Standard/Epistemic initialization and initial dropout RNG state. Retain all runs/failures, no best seed or replacement. Report all five AUROC differences, mean/median/sample SD/min/max, paired dz (null at zero SD), and conditional t4 seed interval. Exact two-sided 32-pattern sign-flip test has minimum attainable p=0.0625, so five pairs cannot establish p<0.05 with that test. A 10,000-draw seed-606 whole-scenario bootstrap preserves ticks/pairs/method alignment and is descriptive with only three validation scenarios. No tick-level pseudo-replication or generalization/superiority claim from one seed. Secondary metrics/condition and NoGraph contrasts remain exploratory.')
section('Conformal Placement','No fitting. Conformal sits after graph method/model-selection and output-pipeline freeze, under a future calibration/exchangeability protocol. All five CAL scenarios stay outside graph training and selection, but already influenced upstream probability calibrators. Reusing them naively as independent split-conformal calibration cannot establish coverage; a later approved protocol must resolve this dependence and temporal/scenario exchangeability. No new data acquisition, upstream refitting or TEST is authorized here.')
section('Kaggle Execution Plan','kaggle_execution_plan.md freezes verification â†’ local FIT pseudo compact export â†’ frozen split validation â†’ future trainer fixture checks â†’ NoGraph/StandardGAT/EpistemicGAT â†’ five paired seeds â†’ checkpoints/predictions/metrics â†’ separately frozen secondary analysis. One T4, deterministic algorithms where supported, no distributed training. Compact N=20 data alone cannot recreate pixel corruptions; local raw TRAIN access is required for the future FIT pseudo exporter, then only compact outputs go to Kaggle. No notebook upload or training was performed.')
hashnames=['protocol.json','graph_schema.json','split_manifest.json','metrics_spec.json','kaggle_execution_plan.md']
section('Frozen Protocol Hashes','\n'.join('- '+n+': `'+sha(OUT/n)+'`' for n in hashnames)+'\n\nAll protocol files, including this report and the minimal writer/integrity records, are listed in SHA256SUMS. Its separate SHA256SUMS.sha256 hashes the complete ledger without self-reference. Protocol dependencies also carry hashes inside protocol.json. Every N=20 cache/handoff byte hash, prior repository hash and frozen synthetic artifact hash matched the initial snapshot. Existing nontraining graph-mechanism tests: 4 passed. No source/test/core changes; only the preregistration report directory was added.')
section('Ready / Not Ready to Generate Graph Training Data','Protocol ready for separately authorized implementation and FIT-only data generation. No graph data has been generated. First validate the future adapter against this frozen schema, source hashes, causal semantics, balancing and exact untouched-parent rules; publish the compact FIT-only export and skip/provenance ledger.')
section('Ready / Not Ready for Kaggle Training','Not ready now: FIT pseudo graph export, tested mini-batch trainer/NoGraph implementation and execution environment lock do not exist yet. No Kaggle upload or training occurred. Protocol readiness is not implementation readiness or authorization to launch.')
section('Recommended Next Step','Authorize only the frozen FIT-derived pseudo/graph compact-export adapter and its integrity validation as the next milestone. Reuse existing clean features and fixed accepted agent mappings. Then assess artifact/trainer readiness before separately authorizing the paired-seed Kaggle run. Stop here: no graph generation, training, TEST, conformal fitting, further acquisition, calibration/feature/recipe changes or commits/pushes.')
doc('report.md','\n'.join(sections)+'\n')
assert len([s for s in sections if s.startswith('# ')])==19
for rel,h in base['repository_sha256'].items():assert sha(ROOT/rel)==h,rel
for p,h in base['N20_cache_and_handoff_sha256'].items():assert sha(p)==h,p
files=sorted(p for p in OUT.iterdir() if p.is_file())
doc('SHA256SUMS',''.join(sha(p)+'  '+p.name+'\n' for p in files))
doc('SHA256SUMS.sha256',sha(OUT/'SHA256SUMS')+'  SHA256SUMS\n')
print('Frozen preregistration complete; protocol SHA256',sha(OUT/'protocol.json'))
print('Graph train:',train);print('Graph validation:',val)
