cloudiness: 5.0
precipitation: 10.0
sun_altitude_angle: 0.0
sun_azimuth_angle: -1.0
fog_density: 1000.0
fog_distance: 0.0
fog_falloff: 0.0
precipitation_deposits: 0.0
wind_intensity: 40.0
wetness: 100.0
scattering_intensity: 1.0
mie_scattering_scale: 0.03
rayleigh_scattering_scale: 0.033100
dust_storm: 10.0